// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppCrud: typeof import('./src/components/AppCrud.vue')['default']
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'Icon:carbon:calendar': typeof import('~icons/carbon/calendar')['default']
    'Icon:carbon:caretDown': typeof import('~icons/carbon/caret-down')['default']
    'Icon:carbon:download': typeof import('~icons/carbon/download')['default']
    'Icon:carbon:generatePdf': typeof import('~icons/carbon/generate-pdf')['default']
    'Icon:carbon:generateXls': typeof import('~icons/carbon/generate-xls')['default']
    'Icon:carbon:search': typeof import('~icons/carbon/search')['default']
    'Icon:carbon:xls': typeof import('~icons/carbon/xls')['default']
    'Icon:carbon:Xls': typeof import('~icons/carbon/-xls')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
